Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2019-11, with the labels that each got.

#2 Added a user manual and a readme.
  Game/Content/Actors/GymCube.uasset
  Game/Content/Geometry/Meshes/1M_Cube.uasset
  Game/Content/Geometry/Meshes/1M_Cube_Chamfer.uasset
  Game/Content/Geometry/Meshes/CubeMaterial.uasset
  Game/Content/Geometry/Meshes/TemplateFloor.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
  Game/Content/Meshes/1M_Cube.uasset
  Game/Content/Meshes/1M_Cube_Chamfer.uasset
  Game/Content/Meshes/CubeMaterial.uasset
  Game/Content/Meshes/TemplateFloor.uasset
  README.md
  USER_MANUAL.md
Labels: size/M

#3 Added FASHandoverGym
  Game/Config/DefaultEngine.ini
  Game/Config/DefaultGame.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Actors/GASCube.uasset
  Game/Content/Actors/GymCube.uasset
  Game/Content/GASComponents/Ability_GrantStackableEffect.uasset
  Game/Content/GASComponents/Effect_Bootstrap.uasset
  Game/Content/GASComponents/Effect_Stackable.uasset
  Game/Content/Maps/FASHandoverGym.umap
  Game/Content/Maps/FASHandoverGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/S

#5 Map to test scenario where unresolved reference are replicated and progressively resolved
  Game/Content/Maps/UnresolvedRefGym.umap
  Game/Content/UnresolvedRef/ActorRefStruct.uasset
  Game/Content/UnresolvedRef/AlwaysRelevantChar.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS
