Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2019-12, with the labels that each got.

#8 Feature/add latency tracing gym
  Game/Content/Characters/LatencyPlayerCharacter_BP.uasset
  Game/Content/GameModes/LatencyGameMode.uasset
  Game/Content/Maps/LatencyGym.umap
  Game/Content/Maps/LatencyGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#10 Update spatialos.json
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#6 GV-144 Adding test gyms for 2 QA workflows tests
  Game/Content/Actors/ReplicatedActor.uasset
  Game/Content/Maps/DestroyStartupActorGym.umap
  Game/Content/Maps/DestroyStartupActorGym_BuiltData.uasset
  Game/Content/Maps/ReplicatedStartupActors.umap
  Game/Content/Maps/ReplicatedStartupActors_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/GV, size/XS

#9 GV-101 - Expand CI build configurations (Test Project)
  Game/Source/GDKTestGymsClient.Target.cs
Labels: jira/GV, size/XS

#12 Made the handover gym hand stuff over.
  Game/Content/LoadBalancing/BP_QuadrantLBStrategy.uasset
  Game/Content/LoadBalancing/BP_VerboseSpatialDebugger.uasset
  Game/Content/Maps/HandoverGym.umap
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#14 Feature/port nfr tests to gym
  Game/Content/Characters/SimulatedPlayers/BenchmarkSimulatedPlayer_BP.uasset
  Game/Content/Maps/BenchmarkGym.umap
  Game/Content/Maps/BenchmarkGym_BuiltData.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/NPCCharacter.cpp
  Game/Source/GDKTestGyms/NPCCharacter.h
Labels: jira/no-ticket, size/XL

#16 Feature/update to 14 3 0
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/GDKTestGyms.uproject
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  spatial/spatialos.json
Labels: jira/no-ticket, size/S

#15 Add Worker Flags Test Gym
  Game/Content/Actors/PrintWorkerFlagsActor.uasset
  Game/Content/Maps/WorkerFlagsGym.umap
  Game/Content/Maps/WorkerFlagsGym_BuiltData.uasset
  USER_MANUAL.md
  spatial/workerflags_testgym_config.json
Labels: jira/no-ticket, size/M
