Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-09, with the labels that each got.

#176 UNR-3908-Tear-Off-Map
  Game/Content/Maps/FunctionalTests/SpatialTearOffMap.umap
Labels: jira/UNR, size/XS

#185 [UNR-3754] Remove asset that used classes and interfaces that will be replaced
  Game/Content/FunctionalTestSamples/BP_1x2_NoInterest_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/BP_1x2_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/BP_TestDelegationGridLBStrategy.uasset
  Game/Content/FunctionalTestSamples/BP_TestDelegationGridLB_NoInterestBorder.uasset
  Game/Content/FunctionalTestSamples/FTEST_06_ActorDelegation.uasset
  Game/Content/FunctionalTestSamples/FTEST_07_ForceInterest.uasset
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationWithoutBorderMap.umap
Labels: jira/UNR, size/XS

#186 UNR-4043 Ensure in zoned test cases player density
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning2_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning3_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning4_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning5_1.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/UNR, size/M

#165 Add hidden actor map/Visibility test
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialNetworkingMap.umap
Labels: jira/no-ticket, size/XS

#190 UNR-4143 Add UnrealTotalAuthoritativePlayers for total players of all workers
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/M

#191 UNR-4226 Change UnrealTotalAuthoritativePlayers to UnrealActivePlayers
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/M

#184 [UNR-4092] Allow tests to take snapshots
  Game/Content/FunctionalTestSamples/FTEST_10_TakeSnapshot.uasset
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart1Map.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart2Map.umap
Labels: jira/UNR, size/XS

#188 Shutdown preparation gym & tests
  Game/Content/Actors/BP_TestPrepareShutdownListener.uasset
  Game/Content/Maps/FunctionalTests/SpatialTestShutdownPreparationMap.umap
  Game/Content/Maps/ShutdownPreparationGym.umap
  Game/Source/GDKTestGyms/Private/ShutdownPreparationGameMode.cpp
  Game/Source/GDKTestGyms/Public/ShutdownPreparationGameMode.h
Labels: jira/no-ticket, size/M

#189 [UNR-4050] Add map to test the debug interface
  Game/Content/Maps/FunctionalTests/TestDebugInterface.umap
Labels: jira/UNR, size/XS

#196 Fix offloaded settings
  Game/Content/LoadBalancing/BP_oflgym_OffloadedSettings.uasset
  Game/Content/LoadBalancing/BP_oflgym_Offloaded_Settings.uasset
Labels: jira/no-ticket, size/XS

#198 fix long debug record compilation issues
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/GDKTestGymsCharacter.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
Labels: jira/no-ticket, size/S

#200 Character using legacy include
  Game/Source/GDKTestGyms/GDKTestGymsCharacter.cpp
Labels: jira/no-ticket, size/XS

#202 include
  Game/Source/GDKTestGyms/GDKTestGymsCharacter.cpp
Labels: jira/no-ticket, size/XS

#197 [gse-1080] spatial prepare test
  Game/Content/FunctionalTestSamples/FTEST_01_RemotePrint.uasset
  Game/Content/FunctionalTestSamples/FTEST_02_CheckOwnership.uasset
  Game/Content/FunctionalTestSamples/FTEST_03_CheckAttack.uasset
  Game/Content/FunctionalTestSamples/FTEST_04_Build.uasset
  Game/Content/FunctionalTestSamples/FTEST_05_ReusableSteps.uasset
  Game/Content/FunctionalTestSamples/FTEST_08_PropertyReplicationRecovery.uasset
  Game/Content/FunctionalTestSamples/FTEST_10_TakeSnapshot.uasset
Labels: jira/no-ticket, size/XS

#206 UNR-4288 Fix DropCube increasing issue
  Game/Content/Benchmark/DropCube_BP.uasset
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning2_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning3_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning4_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning5_1.uasset
Labels: jira/UNR, size/XS

#203 Experimental bad CI
  .buildkite/premerge.definition.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/S
