Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-10, with the labels that each got.

#178 Added the Dynamic Component Test
  .buildkite/premerge.steps.yaml
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialNetworkingMap.umap
Labels: jira/no-ticket, size/XS

#208 Update plane size in SpatialNetworkingMap
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialNetworkingMap.umap
Labels: jira/no-ticket, size/XS

#211 Add config ui input mode test gym
  Game/Content/Controllers/ConfigUIController.uasset
  Game/Content/GameModes/ConfigUIGameMode.uasset
  Game/Content/Maps/SpatialDebuggerConfigUIGym.umap
  Game/Content/UIWidgets/TestMenuUI.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#213 GDK Test Gym updates for the task to add worker information to the boundaries v4.24 compatible
  Game/Config/DefaultGame.ini
  Game/Content/LoadBalancing/BP_QuadrantSmallLBStrategy.uasset
  Game/Content/LoadBalancing/BP_QuadrantSmallZoningSettings.uasset
  Game/Content/LoadBalancing/BP_VerboseSpatialDebugger.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
Labels: jira/UNR, size/XS

#214 Use dash instead of plus in worker json cmdline args
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/S

#205 Add Dynamic Subobject Test Gym
  Game/Content/Actors/DynamicSubobjectTestActor.uasset
  Game/Content/Actors/GASDynamicSubobjectCube.uasset
  Game/Content/Actors/TestDataTable.uasset
  Game/Content/Controllers/GASSmallInterestController.uasset
  Game/Content/GameModes/GameMode_NoInterestGAS.uasset
  Game/Content/Maps/DynamicSubobjectGym.umap
  Game/Content/Maps/FunctionalTests/SpatialDynamicSubobjectMap.umap
Labels: jira/no-ticket, size/XS

#192 Event tracing functional test gym
  Game/Content/FunctionalTestSamples/BP_BasicGameCharacter.uasset
  Game/Content/GameModes/FunctionalTestBasicGameMode.uasset
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#217 Rename ReplicatedStartupActorTest to mark it as a known failing test
  Game/Content/Maps/FunctionalTests/SpatialTestReplicatedStartupActorsMap.umap
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#193 UNR-4045 Add UnrealActorMigration as a new metric for zoning-nfr
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
Labels: jira/UNR, size/L

#220 Change RTT and UpdateTimeDelta unit to milisecond
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
Labels: jira/no-ticket, size/M

#218 UNR-4276 Workaround no longer required
  Game/Content/Maps/benchmarkgym.umap
  Game/Content/Maps/benchmarkgym_BuiltData.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/UNR, size/S
