Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-03, with the labels that each got.

#46 Spawn NPCs slower
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/S

#33 Add lockable character to ability gym to test ownership-based Actor sets
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/GasCharacter_BP.uasset
  Game/Content/Controllers/AbilityLockingController.uasset
  Game/Content/GASComponents/Ability_Counting.uasset
  Game/Content/GameModes/AbilityLockingGameMode.uasset
  Game/Content/Maps/AbilityLockingGym.umap
  Game/Content/Maps/AbilityLockingGym_BuiltData.uasset
  Game/Content/Maps/DestroyStartupActorGym.umap
  Game/Content/Maps/DestroyStartupActorGym_BuiltData.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#48 Feature/native disconnect log
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/M

#47 [UNR-2763] Add a UI to display new latency measurements
  Game/Content/Characters/LatencyPlayerCharacter_BP.uasset
  Game/Content/GameModes/LatencyGameMode.uasset
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Content/Latency/LatencyPlayerController.uasset
  Game/Content/Latency/LatencyUI.uasset
  Game/Content/Maps/LatencyGym.umap
Labels: jira/UNR, size/XS

#49 Connection check was firing immediately
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/S

#51 Feature/more nfr improvements
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/S

#53 Enable NCD interest
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/no-ticket, size/XS

#50 Feature/enable replication graph
  Game/Config/DefaultEngine.ini
  Game/GDKTestGyms.uproject
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
  Game/Source/GDKTestGyms/Public/TestGymsReplicationGraph.h
Labels: jira/no-ticket, size/XXL

#54 Enable result types
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/no-ticket, size/XS

#52 Added DynamicComponents test gym, verbose debugger, user_manual update
  Game/Content/Components/TestDynamicComponent.uasset
  Game/Content/Controllers/DynamicComponentsPlayerController.uasset
  Game/Content/GameModes/DynamicComponentsGameMode.uasset
  Game/Content/LoadBalancing/BP_QuadrantLBStrategy.uasset
  Game/Content/LoadBalancing/BP_VerboseSpatialDebugger.uasset
  Game/Content/Maps/DynamicComponentsGym.umap
  Game/Content/Maps/DynamicComponentsGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/M

#57 Bugfix/native bandwidth cap
  Game/Config/DefaultEngine.ini
Labels: jira/no-ticket, size/XS

#59 Update to 14.5
  Game/Source/GDKTestGyms/Private/SpatialLockingActorComponent.cpp
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#60 Allow 4.23 compilation
  Game/Source/GDKTestGyms/Private/SpatialLockingActorComponent.cpp
Labels: jira/ALLOW, size/XS

#58 Add client net ownership gym
  Game/Content/Actors/ClientNetOwnableCube.uasset
  Game/Content/Controllers/ClientNetOwnershipPlayerController.uasset
  Game/Content/GameModes/ClientNetOwnershipGameMode.uasset
  Game/Content/Maps/ClientNetOwnershipGym.umap
  Game/Content/Maps/ClientNetOwnershipGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#61 Add cube destroy bind for AbilityLockingGym
  Game/Content/Actors/CountingCube.uasset
  Game/Content/Controllers/AbilityLockingController.uasset
  Game/Content/Maps/AbilityLockingGym.umap
  Game/Content/Maps/AbilityLockingGym_BuiltData.uasset
Labels: jira/no-ticket, size/XS

#56 [UNR-2944][MS] TakeDamage cross server gym
  Game/Content/Actors/CrossServerTakeDamageCube.uasset
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer.umap
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer_BuiltData.uasset
  Game/Source/GDKTestGyms/CrossServerTakeDamageActor.cpp
  Game/Source/GDKTestGyms/CrossServerTakeDamageActor.h
  USER_MANUAL.md
Labels: jira/UNR, size/M

#63 Feature/add counter to output
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerAIController_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerCharacter_BP.uasset
  Game/Content/Components/CounterComponent.uasset
  Game/Content/GameModes/BenchmarkGymGameMode.uasset
  Game/Content/Maps/benchmarkgym.umap
Labels: jira/no-ticket, size/XS

#64 Removing NFRGameMode and previous fixed frame rate settings
  Game/Config/DefaultEngine.ini
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/NFRGameMode.cpp
  Game/Source/GDKTestGyms/NFRGameMode.h
Labels: jira/no-ticket, size/M
