Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-01, with the labels that each got.

#13 add locking toggle to handover gym
  Game/Content/Actors/LockableGymCube.uasset
  Game/Content/Controllers/LockingPlayerController.uasset
  Game/Content/GameModes/GDKTestGymsGameMode.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
  Game/Source/GDKTestGyms/Private/SpatialLockingActorComponent.cpp
  Game/Source/GDKTestGyms/Public/SpatialLockingActorComponent.h
  USER_MANUAL.md
Labels: jira/no-ticket, size/M

#19 Make HandoverGym 4.22 compatible
  Game/Content/Actors/LockableGymCube.uasset
  Game/Content/Controllers/LockingPlayerController.uasset
  Game/Content/GameModes/GDKTestGymsGameMode.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
Labels: jira/MAKE, size/XS

#17 Feature/native latency tracing interface fix
  Game/Content/Characters/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#11 Add a test gym for stable references to replicated actors
  Game/Content/Maps/NetReferencesTestGym.umap
  Game/Content/NetReferenceTest/CheckoutPawn.uasset
  Game/Content/NetReferenceTest/CheckoutPawnController.uasset
  Game/Content/NetReferenceTest/ColorMaterial.uasset
  Game/Content/NetReferenceTest/ColorMaterial_Inst.uasset
  Game/Content/NetReferenceTest/CubeWithRefs.uasset
  Game/Content/NetReferenceTest/GameMode_NoInterest.uasset
  Game/Content/NetReferenceTest/NeighbourReference.uasset
  Game/Content/NetReferenceTest/PlayerStateNoInterest.uasset
  Game/Content/NetReferenceTest/SmallInterestController.uasset
  Game/Content/NetReferenceTest/TransparentZone.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#22 Feature/latency tracing properties
  Game/Content/Characters/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#25 Feature/unr 2751 tracer gameplay events
  Game/Content/Characters/LatencyPlayerCharacter_BP.uasset
Labels: jira/UNR, size/XS

#18 [UNR-2583] Test gym for replicating soft reference and asynchronously loaded assets
  Game/Content/Maps/SoftReferenceTestGym.umap
  Game/Content/SoftReferenceTest/Green1.uasset
  Game/Content/SoftReferenceTest/Green2.uasset
  Game/Content/SoftReferenceTest/Green3.uasset
  Game/Content/SoftReferenceTest/Green4.uasset
  Game/Content/SoftReferenceTest/MaterialArray.uasset
  Game/Content/SoftReferenceTest/Red.uasset
  Game/Content/SoftReferenceTest/TestGrid.uasset
  Game/Source/GDKTestGyms/GDKTestGymsBlueprintLibrary.cpp
  Game/Source/GDKTestGyms/GDKTestGymsBlueprintLibrary.h
  USER_MANUAL.md
Labels: jira/UNR, size/S

#21 Configure HandoverGym to use 4-worker grid.
  Game/Config/DefaultEngine.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
Labels: jira/no-ticket, size/XS

#24 Repair broken Test Gym
  Game/Content/NetReferenceTest/NoInterestSpectator.uasset
  Game/Content/NetReferenceTest/SmallInterestController.uasset
Labels: jira/no-ticket, size/XS

#26 Added qbif test gym
  Game/Config/DefaultEngine.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Actors/QBIGymCube.uasset
  Game/Content/Characters/PlayerCharacter_Low_NCD_BP.uasset
  Game/Content/GameModes/QBIFreqGameMode.uasset
  Game/Content/Maps/QBIFreqGym.umap
  Game/Content/QBIFComponents/QBIFRenderComponent.uasset
  Game/GDKTestGyms.uproject
Labels: jira/no-ticket, size/S

#28 Extended the destroy startup actors gym to include a dormant startup actor.
  Game/Content/Actors/DormantActor.uasset
  Game/Content/Actors/ReplicatedActor.uasset
  Game/Content/Maps/DestroyStartupActorGym.umap
  Game/Content/Maps/DestroyStartupActorGym_BuiltData.uasset
  Game/Content/Maps/DestroyStartupActorsGym.umap
  Game/Content/Maps/DestroyStartupActorsGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#23 Feature/UNR-2589 latency tracking
  Game/Config/DefaultGame.ini
  Game/Content/GameModes/LatencyGameMode.uasset
  Game/Content/Maps/LatencyGym.umap
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/UNR, size/S

#29 Update spatialos.json
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS
