Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-12, with the labels that each got.

#240 Change the attack initiation to also check the owner is set
  Game/Content/FunctionalTestSamples/FTEST_03_CheckAttack.uasset
Labels: jira/UNR, size/XS

#242 UNR-3519 - Add ClientTravel Test Gym
  Game/Content/Controllers/ClientTravelController_BP.uasset
  Game/Content/GameModes/ClientTravelGameMode.uasset
  Game/Content/Maps/ClientTravel_Gym.umap
  Game/Content/Maps/ClientTravel_Gym_BuiltData.uasset
  Game/Source/GDKTestGyms/Private/ClientTravelController.cpp
  Game/Source/GDKTestGyms/Public/ClientTravelController.h
  USER_MANUAL.md
Labels: jira/UNR, size/M

#245 Add relevancy test
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialZoningMap.umap
Labels: jira/no-ticket, size/XS

#247 Move zoning map to spatial only tests
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
Labels: jira/no-ticket, size/XS

#246 Update to v15-preview-5
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#249 [UNR-4342] 4.26 Support
  Game/Config/DefaultEngine.ini
  Game/Content/GameModes/AbilityLockingGameMode.uasset
  Game/Content/GameModes/ClientNetOwnershipGameMode.uasset
  Game/Content/GameModes/DynamicComponentsGameMode.uasset
  Game/Content/GameModes/GDKTestGymsGameMode.uasset
  Game/Content/GameModes/MultipleOwnershipGameMode.uasset
  Game/Content/GameModes/QBIFreqGameMode.uasset
  Game/Content/Maps/DestroyStartupActorsGym.umap
  Game/Content/Maps/EmptyGym.umap
  Game/Content/Maps/NetReferencesTestGym.umap
  Game/Content/Maps/NetReferencesTestGym_BuiltData.uasset
  Game/Content/Maps/QBIFreqGym.umap
  Game/Content/Maps/ReplicatedStartupActors.umap
  Game/Content/Maps/ServerTravelGym.umap
  Game/Content/Maps/ServerTravelGym_2.umap
  Game/Content/Maps/SimulatedGameplayTaskGym.umap
  Game/Content/Maps/SoftReferenceTestGym.umap
  Game/Content/Maps/SoftReferenceTestGym_BuiltData.uasset
  Game/Content/Maps/UnresolvedRefGym.umap
  Game/Content/NetReferenceTest/GameMode_NoInterest.uasset
  Game/Content/SimulatedGameplayTask/SimulatedGameplayTaskGameMode.uasset
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.cpp
  Game/Source/GDKTestGyms/DeltaSerializeStruct.h
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Labels: jira/UNR, size/S

#248 UNR-4441 - Add Functional test to handover dynamically set bReplicates
  Game/Content/Maps/FunctionalTests/SpatialTestHandoverReplicationMap.umap
Labels: jira/UNR, size/XS

#252 UNR-4417 Hierarchy Migration Failure Clean Up
  Game/Content/TeleportingGym/TeleportingPlayerController.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#253 Update to preview-6
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#250 [UNR-4482] Update snapshot test map
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart1Map.umap
Labels: jira/UNR, size/XS

#251 TestGym changes for Bug/unr 4245 actors switching workers
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialAuthorityMap.umap
Labels: jira/UNR, size/XS

#257 bug/unr-4274-fix-spatial-authority-map
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialAuthorityMap.umap
Labels: jira/UNR, size/XS
