Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-05, with the labels that each got.

#79 Bugfix/retry if no blackboard
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
Labels: jira/no-ticket, size/S

#80 Create UnrealGDKVersion.txt
  UnrealGDKVersion.txt
Labels: jira/no-ticket, size/XS

#78 Moved latency gym framework to use spawn clustering logic
  Game/Config/DefaultEngine.ini
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Content/Characters/PlayerCharacter_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerCharacter_BP.uasset
  Game/Content/GameModes/BenchmarkGymGameMode.uasset
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Content/Latency/LatencyGameState.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Content/Latency/SimulatedLatencyPlayerCharacter_BP.uasset
  Game/Content/Maps/benchmarkgym.umap
  Game/Content/Maps/latencygym.umap
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/no-ticket, size/S

#85 Feature/ux metric
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerCharacter_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/ControllerIntegerPair.h
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/UserExperienceComponent.h
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
Labels: jira/no-ticket, size/XL

#87 Fix QBI-F results
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/no-ticket, size/XS

#88 Feature/move ux components
  Game/Content/Benchmark/DropCube_BP.uasset
  Game/Content/Benchmark/MulticastComponent_BP.uasset
  Game/Content/Benchmark/PingLoop_BP.uasset
  Game/Content/Characters/PlayerCharacter_BP.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerCharacter_BP.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Content/Latency/SimulatedLatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#90 Adding spawned players metric for GDK
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/M

#93 Add retry conneciton logic
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/no-ticket, size/S

#92 Updating FPS metric to match GDK
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/no-ticket, size/M

#95 Native FPS expectation fixes
  Game/Content/Benchmark/DropCube_BP.uasset
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/no-ticket, size/M
