Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-11, with the labels that each got.

#215 Test Gym updates for better failed hierarchy migration logs
  Game/Content/LoadBalancing/BP_2x1SmallLBStrategy.uasset
  Game/Content/LoadBalancing/BP_2x1SmallZoningSettings.uasset
  Game/Content/Maps/FunctionalTests/SpatialTestCharacterMigrationMap.umap
  Game/Content/TeleportingGym/TeleportingPlayerController.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#216 User Event Tracing
  Game/Content/FunctionalTestSamples/BP_BasicGameCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerComponent.uasset
  Game/Content/GameModes/FunctionalTestBasicGameMode.uasset
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
  Game/Source/GDKTestGyms/Public/EventTracerComponent.h
Labels: jira/no-ticket, size/M

#219 [UNR-4281] Add map for player controller state handover
  Game/Content/Maps/FunctionalTests/SpatialPlayerControllerHandoverMap.umap
Labels: jira/UNR, size/XS

#221 UNR-4405 - Suppress welcome message
  Game/Content/GameModes/BenchmarkGymGameMode.uasset
  Game/Source/GDKTestGyms/BenchmarkGymPlayerState.cpp
  Game/Source/GDKTestGyms/BenchmarkGymPlayerState.h
Labels: jira/UNR, size/S

#225 Fix 'No owning connection' warning in event tracing tests
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
Labels: jira/UNR, size/XS

#224 Separating out EventTracingTestConstants
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerComponent.uasset
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
  Game/Source/GDKTestGyms/Public/EventTracerComponent.h
Labels: jira/no-ticket, size/S

#222 UNR-4426 fix connected clients expectation synchronization issue
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
Labels: jira/UNR, size/L

#226 Fix 'No owning connection' warning in event tracing tests, again
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
Labels: jira/UNR, size/XS

#228 Deployments are checking players when the deployment is being torn down
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/no-ticket, size/XS

#230 Test gym updates for migration test timeout
  Game/Content/Maps/FunctionalTests/SpatialTestCharacterMigrationMap.umap
Labels: jira/UNR, size/XS

#231 Fix for game mode entity not resolving
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/XS

#227 [UNR-4414] Gameplay cues gym
  Game/Config/DefaultGameplayTags.ini
  Game/Content/Characters/GameplayCuesCharacter_BP.uasset
  Game/Content/FX/RadialBurst.uasset
  Game/Content/GASComponents/Ability_ApplyAddGC.uasset
  Game/Content/GASComponents/Ability_ApplyExecuteGC.uasset
  Game/Content/GASComponents/Cue_Add.uasset
  Game/Content/GASComponents/Cue_Execute.uasset
  Game/Content/GASComponents/Effect_AddGC.uasset
  Game/Content/GASComponents/Effect_ExecuteGC.uasset
  Game/Content/GASComponents/Effect_GrantGCAbilities.uasset
  Game/Content/GameModes/GameplayCuesGameMode.uasset
  Game/Content/Maps/GameplayCuesMap.umap
  Game/Source/GDKTestGyms/Private/GasCharacter.cpp
  Game/Source/GDKTestGyms/Public/GasCharacter.h
  USER_MANUAL.md
Labels: jira/UNR, size/M

#237 Downgrade warning: 'RouteAddNetworkActorToNodes: Not Routed'
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Labels: jira/no-ticket, size/XS

#234 Feature/upgrade to v15
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  spatial/spatialos.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.NPCWorker.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/S

#236 bugfix/UNR-3289/Fix spatial commands on workers on native windows
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.NPCWorker.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/UNR, size/S

#239 UNR-4427 enable stat profile via workerflag
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/M

#235 UNR-4165 updated gym to confirm to renamed api in GDK plugin
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/S

#233 Event tracing sampling
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerComponent.uasset
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
  spatial/spatialos.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.NPCWorker.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/M

#229 Test gym updates for select an actor for spatial debugging
  Game/Content/Actors/GymCube.uasset
  Game/Content/LoadBalancing/BP_VerboseSpatialDebugger.uasset
Labels: jira/UNR, size/XS
