Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-07, with the labels that each got.

#119 Feature/gse 1042 add spatial functional test module
  Game/Config/DefaultEditorPerProjectUserSettings.ini
  Game/Content/FunctionalTestSamples/BP_SimpleCharacterTests.uasset
  Game/Content/FunctionalTestSamples/BP_TestBuilding.uasset
  Game/Content/FunctionalTestSamples/FTEST_01_RemotePrint.uasset
  Game/Content/FunctionalTestSamples/FTEST_02_CheckOwnership.uasset
  Game/Content/FunctionalTestSamples/FTEST_03_CheckAttack.uasset
  Game/Content/FunctionalTestSamples/FTEST_04_Build.uasset
  Game/Content/Maps/FunctionalTests/SpatialNetworkingMap.umap
  Game/Content/Maps/FunctionalTests/SpatialZoningMap.umap
Labels: jira/GSE, size/XS

#108 [UNR-2945] Add gym to test asynchronous asset loading in FastArraySerialization-replicated arrays
  Game/Content/DeltaSerializeTest/FASAsyncTestActor.uasset
  Game/Content/DeltaSerializeTest/MaterialSetter.uasset
  Game/Content/Maps/FASAsyncGym.umap
  Game/Source/GDKTestGyms/DeltaSerializeStruct.cpp
  Game/Source/GDKTestGyms/DeltaSerializeStruct.h
  USER_MANUAL.md
Labels: jira/UNR, size/L

#140 Added the map that runs the character movement test
  Game/Content/Maps/FunctionalTests/SpatialTestCharacterMovementMap.umap
Labels: jira/no-ticket, size/XS

#143 [UNR-2987] Add a teleporting Gym
  Game/Content/LoadBalancing/BP_QuadrantLBStrategyWithBorder.uasset
  Game/Content/Maps/TeleportGym.umap
  Game/Content/TeleportingGym/TPGameMode.uasset
  Game/Content/TeleportingGym/TeleportingPlayerController.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#142 Added the map for the Automated Net Reference Gym
  Game/Content/Maps/FunctionalTests/SpatialNetReferenceMap.umap
Labels: jira/no-ticket, size/XS

#139 Adding metric to track the expected number of objects within a scenario
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Content/Components/CounterComponent.uasset
  Game/Content/GameModes/BenchmarkGymGameMode.uasset
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Content/Latency/LatencyGameState.uasset
  Game/Content/OffloadingBenchmark/OffloadingBenchmark_GameMode.uasset
  Game/Content/OffloadingBenchmark/OffloadingBenchmark_GameState.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.cpp
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.h
  Game/Source/GDKTestGyms/Private/CounterComponent.cpp
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/CounterComponent.h
  Game/Source/GDKTestGyms/Public/NFRConstants.h
Labels: jira/UNR, size/XL

#144 Feature/log packet loss
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/no-ticket, size/S

#147 Fixed errors in the test gym game instance.
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/no-ticket, size/XS

#145 Feature/gse 1016 auto destroy actor no interest
  Game/Content/FunctionalTestSamples/Test1x2NoInterestGridStrategy.uasset
  Game/Content/Maps/FunctionalTests/SpatialZoningMap.umap
  Game/Content/Maps/FunctionalTests/SpatialZoningNoInterestMap.umap
Labels: jira/GSE, size/XS

#146 Unr 3761 replicated startup actors test
  Game/Content/Maps/FunctionalTests/SpatialTestReplicatedStartupActorsMap.umap
Labels: jira/no-ticket, size/XS

#150 Updated the USER_MANUAL
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#151 Feature/gse 1212 reusable steps
  Game/Content/FunctionalTestSamples/BP_SimpleCharacterTests.uasset
  Game/Content/FunctionalTestSamples/FTEST_02_CheckOwnership.uasset
  Game/Content/FunctionalTestSamples/FTEST_03_CheckAttack.uasset
  Game/Content/FunctionalTestSamples/FTEST_05_ReusableSteps.uasset
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningBlueprintTests.umap
Labels: jira/GSE, size/XS

#152 Better variance for drop cubes
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/no-ticket, size/XS

#154 Use locking statics
  Game/Content/Actors/LockableGymCube.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGymSettings.uasset
  Game/Content/LoadBalancing/BP_OffloadingBenchmarkGymSettings.uasset
  Game/Content/LoadBalancing/BP_OffloadingGymSettings.uasset
  Game/Content/LoadBalancing/BP_QuadrantZoningSettings.uasset
  Game/Source/GDKTestGyms/Private/SpatialLockingActorComponent.cpp
  Game/Source/GDKTestGyms/Public/SpatialLockingActorComponent.h
Labels: jira/no-ticket, size/M

#161 Fix for locking statics changes
  Game/Content/Actors/OffloadableGymCube.uasset
Labels: jira/no-ticket, size/XS

#163 Update with multi-worker settings bool toggle
  Game/Content/Maps/AbilityLockingGym.umap
  Game/Content/Maps/AbilityLockingGym_BuiltData.uasset
  Game/Content/Maps/ClientNetOwnershipGym.umap
  Game/Content/Maps/ClientNetOwnershipGym_BuiltData.uasset
  Game/Content/Maps/DynamicComponentsGym.umap
  Game/Content/Maps/DynamicComponentsGym_BuiltData.uasset
  Game/Content/Maps/FASHandoverGym.umap
  Game/Content/Maps/FASHandoverGym_BuiltData.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
  Game/Content/Maps/OffloadingBenchmarkGymTiny.umap
  Game/Content/Maps/OffloadingBenchmarkGymTiny_BuiltData.uasset
  Game/Content/Maps/OffloadingGym.umap
  Game/Content/Maps/ServerToServerRPCGym.umap
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer.umap
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer_BuiltData.uasset
  Game/Content/Maps/TeleportGym.umap
  Game/Content/Maps/WorkerFlagsGym.umap
  Game/Content/Maps/benchmarkgym.umap
  Game/Content/Maps/benchmarkgym_BuiltData.uasset
Labels: jira/no-ticket, size/XS

#164 Update with multi-worker settings bool toggle (#163)
  Game/Content/Maps/AbilityLockingGym.umap
  Game/Content/Maps/AbilityLockingGym_BuiltData.uasset
  Game/Content/Maps/ClientNetOwnershipGym.umap
  Game/Content/Maps/ClientNetOwnershipGym_BuiltData.uasset
  Game/Content/Maps/DynamicComponentsGym.umap
  Game/Content/Maps/DynamicComponentsGym_BuiltData.uasset
  Game/Content/Maps/FASHandoverGym.umap
  Game/Content/Maps/FASHandoverGym_BuiltData.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
  Game/Content/Maps/OffloadingBenchmarkGymTiny.umap
  Game/Content/Maps/OffloadingBenchmarkGymTiny_BuiltData.uasset
  Game/Content/Maps/OffloadingGym.umap
  Game/Content/Maps/ServerToServerRPCGym.umap
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer.umap
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer_BuiltData.uasset
  Game/Content/Maps/TeleportGym.umap
  Game/Content/Maps/WorkerFlagsGym.umap
  Game/Content/Maps/benchmarkgym.umap
  Game/Content/Maps/benchmarkgym_BuiltData.uasset
Labels: jira/no-ticket, size/XS

#160 Feature/gse 1220 dynamic actor interest
  Game/Content/FunctionalTestSamples/BP_1x2_NoInterest_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/BP_1x2_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/BP_SimpleCharacterTests.uasset
  Game/Content/FunctionalTestSamples/BP_TestDelegationGridLB_NoInterestBorder.uasset
  Game/Content/FunctionalTestSamples/FTEST_07_ForceInterest.uasset
  Game/Content/FunctionalTestSamples/FTEST_08_PropertyReplicationRecovery.uasset
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningBlueprintTests.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationWithoutBorderMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningVariableReplicationWithoutBorderMap.umap
Labels: jira/GSE, size/XS

#158 CrossServerRPC Test Map
  Game/Content/Maps/FunctionalTests/SpatialTestCrossServerRPCMap.umap
  USER_MANUAL.md
Labels: jira/no-ticket, size/S
