Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-04, with the labels that each got.

#65 Feature/GV-255 Concurrent latency tests with same assembly
  Game/Content/Maps/latencygym.umap
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/GV, size/XS

#69 Feature/re enable native connection saturation
  Game/Config/DefaultEngine.ini
Labels: jira/no-ticket, size/XS

#68 Feature/GV-329 New NFR parameter and new span name format
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/GV, size/XS

#71 Update to 0.9 defaults
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/no-ticket, size/XS

#70 [UNR-3051][MS] Fixing "CreateSavedMove: Hit limit of 96 saved moves" warning.
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerCharacter_BP.uasset
Labels: jira/UNR, size/XS

#66 [UNR-3206] Fix NetReferenceTestGym to manually spawn controller after authority has been gained
  Game/Content/NetReferenceTest/CheckoutPawn.uasset
  Game/Content/NetReferenceTest/CheckoutPawnController.uasset
Labels: jira/UNR, size/XS

#72 [UNR-3209][MS] Adding a gym to test possession and sending RPCs on multiple player controlled actors actors.
  Game/Content/Characters/MultipleOwnershipCube.uasset
  Game/Content/Controllers/MultipleOwnershipController.uasset
  Game/Content/GameModes/MultipleOwnershipGameMode.uasset
  Game/Content/Maps/MultipleOwnershipGym.umap
  Game/Content/Maps/MultipleOwnershipGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#73 Rep graph fix
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Labels: jira/no-ticket, size/XS

#75 update spatialos.json
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#67 Feature/deterministic nfr runs
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerAIController_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerCharacter_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/ControllerIntegerPair.h
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/BlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/BlackboardValues.h
  Game/Source/GDKTestGyms/Public/DeterministicBlackboardValues.h
Labels: jira/no-ticket, size/L

#77 RYDER 4 LYF
  .gitignore
Labels: jira/no-ticket, size/XS
