Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-08, with the labels that each got.

#167 Improving drop cube variance.
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/no-ticket, size/XS

#168 UNR-3925: Use valid ip address
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
Labels: jira/UNR, size/XS

#166 UNR-3761/Client-Net-Ownership-Gym-Automation-Map
  Game/Content/Maps/FunctionalTests/SpatialTestNetOwnershipMap.umap
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#169 Set the teleport gym with a quadrant load balancing configuration
  Game/Content/Maps/TeleportGym.umap
Labels: jira/no-ticket, size/XS

#155 Shipping logs + cmd line
  Game/Source/GDKTestGyms.Target.cs
  Game/Source/GDKTestGymsClient.Target.cs
  Game/Source/GDKTestGymsServer.Target.cs
Labels: jira/no-ticket, size/XS

#171 Fix regular builds
  Game/Source/GDKTestGyms.Target.cs
  Game/Source/GDKTestGymsClient.Target.cs
  Game/Source/GDKTestGymsServer.Target.cs
Labels: jira/no-ticket, size/S

#172 Fixing actor delegation test
  Game/Content/FunctionalTestSamples/FTEST_06_ActorDelegation.uasset
Labels: jira/GSE, size/XS

#175 Disable VR Plugins
  Game/GDKTestGyms.uproject
Labels: jira/no-ticket, size/XS

#179 Changed the maps Testing Mode to "Use Current Settings"
  Game/Content/Maps/FunctionalTests/SpatialNetReferenceMap.umap
  Game/Content/Maps/FunctionalTests/SpatialNetworkingMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestCharacterMovementMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestCrossServerRPCMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestNetOwnershipMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestReplicatedStartupActorsMap.umap
  Game/Content/Maps/FunctionalTests/SpatialZoningMap.umap
  Game/Content/Maps/FunctionalTests/SpatialZoningNoInterestMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningBlueprintTests.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationWithoutBorderMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningVariableReplicationWithoutBorderMap.umap
Labels: jira/no-ticket, size/XS

#173 UNR-3761-World-Composition-Gym-Automation
  Game/Content/Maps/WorldComposition/InitiallyDomantActorLevel.umap
  Game/Content/Maps/WorldComposition/InitiallyDomantActorLevel_BuiltData.uasset
  Game/Content/Maps/WorldComposition/InitiallyDomantAndNetLoadLeveL.umap
  Game/Content/Maps/WorldComposition/InitiallyDomantAndNetLoadLeveL_BuiltData.uasset
  Game/Content/Maps/WorldComposition/NetLoadOnClientLevel.umap
  Game/Content/Maps/WorldComposition/NetLoadOnClientLevel_BuiltData.uasset
  Game/Content/Maps/WorldComposition/ReplicatedActorLEvel.umap
  Game/Content/Maps/WorldComposition/ReplicatedActorLEvel_BuiltData.uasset
  Game/Content/Maps/WorldComposition/WorldCompositionGym.umap
  Game/Content/Maps/WorldComposition/WorldCompositionGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#170 Modified the ReplicatedStartupActor Map.
  Game/Content/Maps/FunctionalTests/SpatialTestReplicatedStartupActorsMap.umap
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#183 Test/spatial test rep notify
  Game/Content/Maps/FunctionalTests/SpatialNetworkingMap.umap
Labels: jira/no-ticket, size/XS

#182 UNR-4036 Change GridBaseLBStrategy setting files for zoning-nfrs
  Game/Content/LoadBalancing/BP_BenchmarkGym_Settings_Zoning2_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Settings_Zoning3_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Settings_Zoning4_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Settings_Zoning5_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning2_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning3_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning4_1.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning5_1.uasset
Labels: jira/UNR, size/XS

#181 UNR-3761/Handover-Gym-Automation-Map
  Game/Content/Maps/FunctionalTests/SpatialHandoverMap.umap
  USER_MANUAL.md
Labels: jira/UNR, size/XS
