Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-06, with the labels that each got.

#104 Remove force net update from VL measurement
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
Labels: jira/no-ticket, size/XS

#100 FPS metric using the game windowed FPS
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
Labels: jira/no-ticket, size/L

#105 Merge/fps metric equality
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
Labels: jira/no-ticket, size/L

#115 Update pinned runtime and templates
  DeployGame.bat
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/two_worker_test.json
Labels: jira/no-ticket, size/XS

#112 Benchmark gym offloading
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Content/Benchmark/OffloadedDropCube_BP.uasset
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Content/Characters/SimulatedPlayers/OffloadedNPCAIController_BP.uasset
  Game/Content/Maps/benchmarkgym.umap
  Game/Content/Maps/benchmarkgym_BuiltData.uasset
  Game/Content/OffloadedDropCube_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.cpp
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.h
Labels: jira/no-ticket, size/M

#121 Mergefix/version
  UnrealGDKVersion.txt
Labels: jira/no-ticket, size/XS

#117 Fix spawning on NPC worker
  Game/Content/Maps/benchmarkgym.umap
  Game/Content/Maps/benchmarkgym_BuiltData.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/S

#125 Logic fix
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/XS

#126 Remove authority check from TryAddSpatialMetrics
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/XS

#127 Fix spawning for benchmark gym offloading
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/XS

#128 Better handle actor deletion
  Game/Content/Benchmark/DropCube_BP.uasset
Labels: jira/no-ticket, size/XS

#114 Make egress scenario more comparable on both frameworks
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/UserExperienceComponent.h
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
  LaunchNFRServer.bat
  LaunchSpatial.bat
Labels: jira/no-ticket, size/L

#132 Bugfix/alter cube lifespan
  Game/Content/Benchmark/DropCube_BP.uasset
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
Labels: jira/no-ticket, size/XS

#130 Fix log
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/no-ticket, size/XS

#129 [UNR-3678][MS] Consistent metric timers for GDK and native
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
Labels: jira/UNR, size/L

#133 Introducing expected players instead of player count for NFR tests
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/no-ticket, size/S

#134 Update 0.10.0-rc from master
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Benchmark/DropCube_BP.uasset
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/BenchmarkGymNPCSpawner.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
  Game/Source/GDKTestGyms/Public/UserExperienceComponent.h
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
  LaunchNFRServer.bat
  LaunchSpatial.bat
Labels: jira/no-ticket, size/XL

#131 UNR-3689 - Update gym user guide for new worker instance launching UI
  Game/Content/Maps/ClientNetOwnershipGym.umap
  Game/Content/Maps/ClientNetOwnershipGym_BuiltData.uasset
  Game/Content/Maps/DynamicComponentsGym.umap
  Game/Content/Maps/DynamicComponentsGym_BuiltData.uasset
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer.umap
  Game/Content/Maps/ServerToServerTakeDamageRPCGymCrossServer_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/S

#135 [UNR-3718][MS] Adding clarity to the multiple ownership gym
  Game/Content/Controllers/MultipleOwnershipController.uasset
  Game/Content/Maps/MultipleOwnershipGym.umap
  Game/Content/Maps/MultipleOwnershipGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#138 Merge master into 0.10.0-rc
  Game/Content/Controllers/MultipleOwnershipController.uasset
  Game/Content/Maps/MultipleOwnershipGym.umap
  Game/Content/Maps/MultipleOwnershipGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS
