Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2020-02, with the labels that each got.

#27 Add GameplayAbility Locking Gym
  Game/Content/Actors/CountingCube.uasset
  Game/Content/Actors/GymCube.uasset
  Game/Content/Controllers/AbilityLockingController.uasset
  Game/Content/GASComponents/Ability_Counting.uasset
  Game/Content/GASComponents/Effect_GrantCounting.uasset
  Game/Content/GameModes/AbilityLockingGameMode.uasset
  Game/Content/Maps/AbilityLockingGym.umap
  Game/Content/Maps/AbilityLockingGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#34 Bugfix/double npc spawns
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: jira/no-ticket, size/S

#35 UNR-2898 - Update max player/spectator number
  Game/Config/DefaultGame.ini
Labels: jira/GV, jira/UNR, size/XS

#31 server to server RPC gym
  Game/Content/Actors/CrossServerCube.uasset
  Game/Content/Maps/ServerToServerRPCGym.umap
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#32 World composition gym
  Game/Content/Maps/WorldComposition/InitiallyDomantActorLevel.umap
  Game/Content/Maps/WorldComposition/InitiallyDomantActorLevel_BuiltData.uasset
  Game/Content/Maps/WorldComposition/InitiallyDomantAndNetLoadLeveL.umap
  Game/Content/Maps/WorldComposition/InitiallyDomantAndNetLoadLeveL_BuiltData.uasset
  Game/Content/Maps/WorldComposition/NetLoadOnClientLevel.umap
  Game/Content/Maps/WorldComposition/NetLoadOnClientLevel_BuiltData.uasset
  Game/Content/Maps/WorldComposition/ReplicatedActorLEvel.umap
  Game/Content/Maps/WorldComposition/ReplicatedActorLEvel_BuiltData.uasset
  Game/Content/Maps/WorldComposition/WorldCompositionGym.umap
  Game/Content/Maps/WorldComposition/WorldCompositionGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#7 Feature/unr 2469 server travel gym
  Game/Content/Actors/ServerTravelCube.uasset
  Game/Content/Maps/ServerTravelGym.umap
  Game/Content/Maps/ServerTravelGym_2.umap
  Game/Content/Maps/ServerTravelGym_2_BuiltData.uasset
  Game/Content/Maps/ServerTravelGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#36 Added nav mesh, and centralized npc/sim player logic
  Game/Content/Characters/SimulatedPlayers/BenchmarkSimulatedPlayer_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerAIController_BP.uasset
  Game/Content/Maps/BenchmarkGym.umap
  Game/Content/Maps/BenchmarkGym_BuiltData.uasset
  Game/Source/GDKTestGyms/NPCCharacter.cpp
  Game/Source/GDKTestGyms/NPCCharacter.h
Labels: jira/no-ticket, size/M

#37 Fix world size and increased ground plane size in BenchmarkGym
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/two_worker_test.json
  spatial/workerflags_testgym_config.json
Labels: size/S

#38 Reset sensible spatial gdk defaults for NFR pipeline
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/no-ticket, size/XS

#39 Set simulated pawn class
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/no-ticket, size/XS

#40 Add fps output, used by NFR pipeline
  Game/Config/DefaultEngine.ini
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  LaunchSimClient.bat
Labels: jira/no-ticket, size/M

#41 Add SimulatedGameplayTask gym
  Game/Content/Maps/SimulatedGameplayTaskGym.umap
  Game/Content/Maps/SimulatedGameplayTaskGym_BuiltData.uasset
  Game/Content/SimulatedGameplayTask/Ability_RunSimulatedTask.uasset
  Game/Content/SimulatedGameplayTask/Effect_GiveAbility_RunSimulatedTask.uasset
  Game/Content/SimulatedGameplayTask/SimulatedGameplayTaskGameMode.uasset
  Game/Content/SimulatedGameplayTask/SimulatedGameplayTaskPawn.uasset
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/Private/GASPawn.cpp
  Game/Source/GDKTestGyms/Private/Task_DelaySimulated.cpp
  Game/Source/GDKTestGyms/Public/GASPawn.h
  Game/Source/GDKTestGyms/Public/Task_DelaySimulated.h
  USER_MANUAL.md
Labels: jira/UNR, size/L

#42 [UNR-2978][MS] Removing building of SimPlayers from BuildWorker.bat
  BuildProject.bat
Labels: jira/UNR, size/XS

#43 Removing max FPS
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
Labels: jira/no-ticket, size/XS
