Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-02, with the labels that each got.

#305 UNR-4874 Count auth PlayerController for client_stayed_connection check
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/S

#300 UNR-4822 Fix TestGyms branch detection in CI
  .buildkite/premerge.definition.yaml
  .buildkite/premerge.steps.yaml
  ci/generate-pipeline-steps.sh
  ci/premerge.template.steps.yaml
Labels: jira/UNR, size/M

#306 UNR-4447: Added a new handover test and ported the old test to 4.24
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialTestHandoverActorComponentReplicationMap.umap
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialTestHandoverDynamicReplicationMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestHandoverReplicationMap.umap
Labels: jira/UNR, size/XS

#308 Feature/add async package loading gym
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/AsyncPackageLoadingTest/AsyncActor.uasset
  Game/Content/AsyncPackageLoadingTest/AsyncGameMode.uasset
  Game/Content/Maps/AsyncPackageLoadingGym.umap
  Game/Source/GDKTestGyms/Private/AsyncActorSpawner.cpp
  Game/Source/GDKTestGyms/Private/AsyncPlayerController.cpp
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
  Game/Source/GDKTestGyms/Public/AsyncActorSpawner.h
  Game/Source/GDKTestGyms/Public/AsyncPlayerController.h
  USER_MANUAL.md
Labels: jira/no-ticket, size/L

#311 Disable audio logs
  Game/Config/DefaultEngine.ini
Labels: jira/no-ticket, size/XS

#313 Disable CrossServerAbilityActivationTest while it's failing
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
Labels: jira/no-ticket, size/XS

#312 Add copyright notice to project settings, fix files missing the notice
  Game/Config/DefaultGame.ini
  Game/Source/GDKTestGyms/CrossServerTakeDamageActor.cpp
  Game/Source/GDKTestGyms/CrossServerTakeDamageActor.h
  Game/Source/GDKTestGyms/Private/AsyncActorSpawner.cpp
  Game/Source/GDKTestGyms/Private/AsyncPlayerController.cpp
  Game/Source/GDKTestGyms/Private/CounterComponent.cpp
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/AsyncActorSpawner.h
  Game/Source/GDKTestGyms/Public/AsyncPlayerController.h
  Game/Source/GDKTestGyms/Public/BlackboardValues.h
  Game/Source/GDKTestGyms/Public/CounterComponent.h
  Game/Source/GDKTestGyms/Public/DeterministicBlackboardValues.h
  Game/Source/GDKTestGyms/Public/NFRConstants.h
  Game/Source/GDKTestGyms/Public/UserExperienceComponent.h
  Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
Labels: jira/no-ticket, size/S

#307 [UNR-2626] Ability Giving Gym
  Game/Content/Characters/AbilityGivingGymCharacter_BP.uasset
  Game/Content/GASComponents/Ability_Server_PrintOnActivate.uasset
  Game/Content/GameModes/AbilitySpecHandleGameMode.uasset
  Game/Content/Maps/AbilityGivingGym.umap
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/Private/AbilityGivingGymCharacter.cpp
  Game/Source/GDKTestGyms/Public/AbilityGivingGymCharacter.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestPawnBase.cpp
  USER_MANUAL.md
Labels: jira/UNR, size/M

#301 [UNR-4658] Remove functional test CI maps
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialAuthorityMap.umap
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialComponentMap.umap
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialNetworkingMap.umap
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialCleanupConnectionTest.umap
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialTestHandoverActorComponentReplicationMap.umap
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialTestHandoverDynamicReplicationMap.umap
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
  Game/Source/GDKTestGymsFunctionalTests/GDKTestGymsFunctionalTests.Build.cs
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/Spatial2WorkerTestGymMap.cpp
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/Spatial2WorkerTestGymMap.h
Labels: jira/UNR, size/M

#310 Instrument latency paths
  Game/Content/FunctionalTestSamples/BP_eventTracerCrossServerCube.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Content/Maps/SpatialEventTracingZoningTests.umap
Labels: jira/UNR, size/XS

#315 Re-enable cross server ability activation test
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/Spatial2WorkerTestGymMap.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/CrossServerAbilityActivationTest.cpp
Labels: jira/no-ticket, size/XS

#317 [UNR-4833] Fix gameplay cues test
  Game/Config/DefaultGame.ini
  Game/Config/DefaultGameplayTags.ini
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/Spatial2WorkerTestGymMap.cpp
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/SpatialSingleWorkerTestGymMap.cpp
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/SpatialSingleWorkerTestGymMap.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GA_ApplyCueEffect.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GC_SignalCueActivation.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/PredictedGameplayCuesTest.cpp
Labels: jira/UNR, size/M

#316 Adding ET to NFRs
  Game/Content/EventTracing/BP_ETSamplingSettings_benchmarkgym.uasset
  Game/Content/EventTracing/BP_ETSamplingSettings_latencygym.uasset
  Game/Content/EventTracing/BP_ETSamplingSettings_oflgym.uasset
Labels: jira/UNR, size/XS

#319 UNR-4936 Add a new gym for uptime test
  Game/Content/Benchmark/UptimeGymGameState.uasset
  Game/Content/GameModes/UptimeGymGameMode.uasset
  Game/Content/Maps/uptimegym.umap
Labels: jira/UNR, size/XS
