Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-03, with the labels that each got.

#314 Override test settings
  Game/Config/MapSettingsOverrides/TestOverridesBase.ini
  Game/Config/MapSettingsOverrides/TestOverridesControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesEmpty.ini
  Game/Config/MapSettingsOverrides/TestOverridesLocalControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesLockedControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesMultiControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialCoreModeReplicationMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingTests.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingZoningTests.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialNetReferenceMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialPlayerControllerHandoverMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialSnapshotTestPart1Map.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialSnapshotTestPart2Map.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialTearOffMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialTestCharacterMigrationMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialTestShutdownPreparationMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialZoningMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesTestDebugInterface.ini
  Game/Config/MapSettingsOverrides/TestOverridesWorldCompositionGym.ini
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  Game/Content/Maps/FunctionalTests/SpatialNetReferenceMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart1Map.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart2Map.umap
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/CrossServerAbilityActivationTest.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/PredictedGameplayCuesTest.cpp
  USER_MANUAL.md
Labels: jira/UNR, size/M

#320 UNR-4915 setup gym UnrealClient to have limited permissions in launch config
  spatial/default_launch.json
Labels: jira/UNR, size/S

#324 Remove maps for tests that have C++ generated ones
  Game/Content/Maps/FunctionalTests/RemotePossession/ControllerPossessPawnGym.umap
  Game/Content/Maps/FunctionalTests/RemotePossession/LocalControllerPossessPawnGym.umap
  Game/Content/Maps/FunctionalTests/RemotePossession/LockedControllerPossessPawnGym.umap
  Game/Content/Maps/FunctionalTests/RemotePossession/MultiControllerPossessPawnGym.umap
  Game/Content/Maps/FunctionalTests/SpatialHandoverMap.umap
  Game/Content/Maps/FunctionalTests/SpatialNetReferenceMap.umap
  Game/Content/Maps/FunctionalTests/SpatialPlayerControllerHandoverMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTearOffMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestCharacterMigrationMap.umap
  Game/Content/Maps/FunctionalTests/SpatialTestNetOwnershipMap.umap
  Game/Content/Maps/FunctionalTests/SpatialZoningNoInterestMap.umap
  Game/Content/Maps/FunctionalTests/TestDebugInterface.umap
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/Spatial2WorkerTestGymMap.cpp
Labels: jira/UNR, size/XS

#325 Fix crash in AbstractSpatialMultiWorkerSettings when running ZoningBlueprintTests
  Game/Content/FunctionalTestSamples/BP_1x2_NoInterest_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/BP_1x2_SmallInterest_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/BP_1x2_WorkerSettings.uasset
  Game/Content/FunctionalTestSamples/Test1x2NoInterestGridStrategy.uasset
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningBlueprintTests.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationWithoutBorderMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningVariableReplicationWithoutBorderMap.umap
  Game/Content/Maps/MultiworkerWorldComposition/MultiworkerWorldComposition.umap
Labels: jira/no-ticket, size/XS

#323 Setup ET sampling settings for latency gym
  Game/Content/EventTracing/BP_ETSamplingSettings_latencygym.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#327 UNR-5163 updated runtime to 15.0.1
  LaunchSpatial.bat
  spatial/spatialos.json
Labels: jira/UNR, size/XS

#328 Add missing header
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/XS

#331 Reduce latency et sampling
  Game/Content/EventTracing/BP_ETSamplingSettings_latencygym.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#330 Re-add the soft references gym to the manual
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#329 MBL-219 make the spawn zones' rows,cols,width and height to be agile
  Game/Config/DefaultEngine.ini
  Game/Content/GameModes/UptimeGymGameMode.uasset
  Game/Content/Maps/uptimegym.umap
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/AUptimeGameMode.h
Labels: jira/MBL, size/L

#332 [MBL-222]Call memreport on a configurable interval on the server worker
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/MBL, size/M

#334 De-duplicate test gym auto execution steps
  USER_MANUAL.md
Labels: jira/no-ticket, size/M

#336 [Fix] Shut down Memreport Flag in Shipping build
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/no-ticket, size/S

#337 Modified test map to include new test
  Game/Content/Maps/SpatialEventTracingZoningTests.umap
Labels: jira/UNR, size/XS

#338 Trigger the new CI pipeline without branch detection
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/S

#340 Trigger the new CI pipeline without branch detection (FIXED)
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#333 [MBL-220] manage egress configuration through worker flags
  Game/Content/Benchmark/UptimeGymGameState.uasset
  Game/Content/Characters/SimulatedPlayers/UptimeSimlulatedPlayerCharacter_BP.uasset
  Game/Content/Characters/UptimePlayerCharacter_BP.uasset
  Game/Content/GameModes/UptimeGymGameMode.uasset
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/AUptimeGameMode.h
  Game/Source/GDKTestGyms/AUptimeGymsCharacter.cpp
  Game/Source/GDKTestGyms/AUptimeGymsCharacter.h
Labels: jira/MBL, size/M
