Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-07, with the labels that each got.

#435 Revert #418
  .buildkite/premerge.definition.yaml
Labels: jira/no-ticket, size/XS

#434 Bug/fix profile
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/M

#436 [UNR-5789] Fix gameplay debugger non-spatial-specific test notes
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#437 [UNR-5791] Gameplay Debugger tracks focused actor across interest boundaries
  Game/Content/Maps/GameplayDebugger/GameplayDebuggerManualTest.umap
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#438 [UNR-5791] Gameplay Debugger tracks focused actor across interest boundaries
  Game/Content/Maps/GameplayDebugger/GameplayDebuggerManualTest.umap
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#440 Altered bandwidth usage in Bandwidth test
  .gitignore
  Game/Content/Benchmark/ReplicatedComponent_BP.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/no-ticket, size/M

#444 Add ready checks before calling multicast ping
  Game/Content/Benchmark/MulticastComponent_BP.uasset
Labels: jira/no-ticket, size/XS

#439 [UNR-5436] Feature/map generation upon startup
  Game/Source/GDKTestGymsFunctionalTests/GDKTestGymsFunctionalTests.cpp
  Game/Source/GDKTestGymsFunctionalTests/GDKTestGymsFunctionalTests.h
Labels: jira/UNR, size/S

#442 Update default CI branch to 0.14.0-rc
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#441 Use new CI versioned against main
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#445 Move ini file overrides
  Game/Config/NFROverrides/DefaultEngine.diff.ini
  Game/Config/NFROverrides/DefaultGame.diff.ini
  Game/Config/NFROverrides/DefaultSpatialGDKSettings-CN.diff.ini
  Game/Config/NFROverrides/DefaultSpatialGDKSettings.diff.ini
Labels: jira/no-ticket, size/S

#446 Alter bandwidth usage
  Game/Content/Characters/PlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#448 Adding new setting that will be tested via EventTracingSettingsOverri…
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingGroup.ini
Labels: jira/UNR, size/XS

#449 Fix checks for multiple actor counts
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/no-ticket, size/S

#451 Reduce required migration in NFRs
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/no-ticket, size/XS

#443 UNR-5571 native scenario can be run in our new platform
  Game/Config/DefaultEngine.ini
  Game/GDKTestGyms.uproject
  Game/Plugins/MetricsServiceProvider/Config/FilterPlugin.ini
  Game/Plugins/MetricsServiceProvider/MetricsServiceProvider.uplugin
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/MetricsServiceProvider.Build.cs
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Private/MetricsBlueprintLibrary.cpp
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Private/MetricsServiceModule.cpp
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Private/MetricsServiceProvider.h
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Private/PrometheusServer.cpp
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Public/MetricsBlueprintLibrary.h
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Public/MetricsServiceModule.h
  Game/Plugins/MetricsServiceProvider/Source/MetricsServiceProvider/Public/PrometheusServer.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/GDKTestGyms.Build.cs
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Labels: jira/UNR, size/XXL

#453 Adding functional tests to test ET settings
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
  Game/Source/GDKTestGyms/Public/EventTracerComponent.h
Labels: jira/UNR, size/M

#450 [UNR-5775] Fix actor count metric being incorrectly reported
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
  Game/Source/GDKTestGyms/Public/TestGymsReplicationGraph.h
Labels: jira/UNR, size/S

#458 Re-add actor count and revert recent AlwaysReplicate change
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Content/OffloadingBenchmark/OffloadingBenchmark_GameState.uasset
  Game/Source/GDKTestGyms/Private/CounterComponent.cpp
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
  Game/Source/GDKTestGyms/Public/CounterComponent.h
  Game/Source/GDKTestGyms/Public/TestGymsReplicationGraph.h
Labels: jira/no-ticket, size/M
