Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-06, with the labels that each got.

#404 [UNR-5620] Fix simulated player movement
  Game/Content/Characters/SimulatedPlayers/BTTask_BenchmarkNPC_SwapTarget.uasset
Labels: jira/UNR, size/XS

#387 [UNR-5447] Replace Handover with ServerOnly replication condition
  Game/Content/Actors/CountingCube.uasset
  Game/Content/Actors/GASCube.uasset
  Game/Content/Actors/GymCube.uasset
  Game/Content/Actors/NoNetLoadGymCube.uasset
  Game/Content/Actors/PrintWorkerFlagsActor.uasset
  Game/Content/Actors/ServerTravelCube.uasset
  Game/Content/Actors/VisualLoggerGymCube.uasset
  Game/Content/Actors/VisualLoggerStationaryGymCube.uasset
  Game/Content/Benchmark/DropCube_BP.uasset
  Game/Content/TeleportingGym/TeleportingPlayerController.uasset
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestActorBase.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestActorBase.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestPawnBase.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestPawnBase.h
Labels: jira/UNR, size/S

#406 Remove old CLI flags from test override
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingTests.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingZoningTests.ini
Labels: jira/UNR, size/XS

#407 Fix generate schema error by replace handover with server only tag.
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/DeterministicBlackboardValues.h
Labels: jira/no-ticket, size/XS

#405 Allow use of STATs in testing
  Game/Source/GDKTestGyms.Target.cs
  Game/Source/GDKTestGymsClient.Target.cs
  Game/Source/GDKTestGymsServer.Target.cs
Labels: jira/no-ticket, size/S

#409 [UNR-5589] Fix memreport trigger in Test configuation
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/S

#412 [UNR-5088] Remove map SpatialDynamicSubobjectMap
  Game/Content/Maps/FunctionalTests/SpatialDynamicSubobjectMap.umap
Labels: jira/UNR, size/XS

#413 [UNR-5655] Fix bp warning msg on local deployment
  Game/Content/Characters/SimulatedPlayers/BTTask_BenchmarkNPC_SwapTarget.uasset
Labels: jira/UNR, size/XS

#375 Cleaning up Actor count metric and making it functional in zoning
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
  Game/Content/Characters/PlayerCharacter_BP.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/AUptimeGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/CounterComponent.cpp
  Game/Source/GDKTestGyms/Public/CounterComponent.h
Labels: jira/UNR, size/XL

#395 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/UNR, size/S

#414 Correct the Latency Gym user manual
  USER_MANUAL.md
Labels: jira/UNR, size/S

#417 Call super OnAuthorityGained in Latency Character
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#410 Merge 0.13.1 into master
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingGroup.ini
  Game/Content/EventTracing/BP_ETSamplingSettings_Default.uasset
  Game/Content/EventTracing/BP_ETSamplingSettings_latencygym.uasset
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
  USER_MANUAL.md
Labels: jira/no-ticket, size/M

#416 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#421 Reduce clusters on boundaries
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/no-ticket, size/XS

#418 Makes `dry-run/*`, `skip-ci/`, `doc/*` & `docs/*` branches exempt from premerge
  .buildkite/premerge.definition.yaml
Labels: jira/UNR, size/XS

#422 Update to CI 1.4
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#425 Decrease server move frequency
  Game/Config/DefaultGame.ini
Labels: jira/no-ticket, size/XS

#426 Explicitly initialize ActorCount variables in constructor
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/UNR, size/XS

#428 Reset WorldCompositionGym map game mode to default
  Game/Content/Maps/WorldComposition/WorldCompositionGym.umap
  Game/Content/Maps/WorldComposition/WorldCompositionGym_BuiltData.uasset
Labels: jira/UNR, size/XS

#420 Generic grid spawning in test gyms project
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
  Game/Content/Characters/SimulatedPlayers/OffloadedNPCAIController_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerAIController_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerBehaviorTree_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerBlackboard_BP.uasset
  Game/Content/Characters/UptimePlayerCharacter_BP.uasset
  Game/Content/GameModes/BenchmarkGymGameMode.uasset
  Game/Content/GameModes/UptimeGymGameMode.uasset
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Settings_Zoning2_2.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning2_2.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning3_3.uasset
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/AUptimeGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/BlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/BlackboardValues.h
Labels: jira/no-ticket, size/XXL

#431 [UNR-5538] Gameplay Debugger test gym and notes
  Game/Content/Actors/GameplayDebuggerGymCube.uasset
  Game/Content/GameplayDebugger/EQS_GameplayDebugger_FindRandomLocation.uasset
  Game/Content/Maps/GameplayDebugger/GameplayDebuggerManualTest.umap
  USER_MANUAL.md
Labels: jira/UNR, size/M

#432 UNR-5777 gameplay debugger backports
  Game/Content/Actors/GameplayDebuggerGymCube.uasset
  Game/Content/GameplayDebugger/EQS_GameplayDebugger_FindRandomLocation.uasset
  Game/Content/Maps/GameplayDebugger/GameplayDebuggerManualTest.umap
  USER_MANUAL.md
Labels: jira/UNR, size/M
