Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-11, with the labels that each got.

#456 [UNR-5808] High level event tracing
  Game/Content/Characters/GasCharacter_BP.uasset
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Content/Latency/LatencyGameState.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Content/Latency/SimulatedLatencyPlayerCharacter_BP.uasset
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/LatencyTracer.cpp
  Game/Source/GDKTestGyms/Private/MazeGenerator.cpp
  Game/Source/GDKTestGyms/Public/LatencyPayload.h
  Game/Source/GDKTestGyms/Public/LatencyTracer.h
Labels: jira/UNR, size/L

#474 [UNR-5965] Remove manual Net reference test gym
  Game/Content/Maps/NetReferencesTestGym.umap
  Game/Content/Maps/NetReferencesTestGym_BuiltData.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#475 Only create latency tracer when needed
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
  Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
  Game/Source/GDKTestGyms/Private/LatencyTracer.cpp
  Game/Source/GDKTestGyms/Public/LatencyTracer.h
Labels: size/S, jira/no-ticket

#455 Add Flag To Not Queue With Unresolved Params Test
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/BP_MulticastBroadcasterDoNotQueue.uasset
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/BP_MulticastReceiverDoNotQueue.uasset
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/DoNotQueueLBStrategy.uasset
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/DoNotQueueReceiverTarget.uasset
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/DoNotQueueSpatialMultiWorkerSettings.uasset
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/FTEST_DoNotQueueFlagTest.uasset
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/LM_DoNotQueue.umap
  Game/Content/Maps/FunctionalTests/DoNotQueueTest/TestTreeRef.uasset
  Game/GDKTestGyms.uproject
Labels: size/XS, jira/no-ticket

#478 [INT-57] Zero-initialize UProperties to remove some warnings
  Game/Source/GDKTestGyms/Public/BlackboardValues.h
  Game/Source/GDKTestGyms/Public/MazeGenerator.h
Labels: size/XS, jira/INT

#477 Feature/enable entity id interest
  .gitignore
  Game/Config/DefaultGame.ini
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Config/NFROverrides/DefaultSpatialGDKSettings.diff.ini
  Game/Content/Benchmark/Disco387GameState_BP.uasset
  Game/Content/Benchmark/Disco387PlayerState.uasset
  Game/Content/Benchmark/ReplicatedComponent_BP.uasset
  Game/Content/Characters/ClientAuthPlayerCharacter_BP.uasset
  Game/Content/Characters/PlayerCharacter_BP.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedClientAuthPlayerCharacter_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerBehaviorTree_BP.uasset
  Game/Content/Characters/UptimePlayerCharacter_BP.uasset
  Game/Content/GameModes/Disco387GymGameMode.uasset
  Game/Content/Maps/Disco387.umap
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/Disco387GameStateBase.cpp
  Game/Source/GDKTestGyms/Private/LatencyTracer.cpp
  Game/Source/GDKTestGyms/Private/ShutdownPreparationGameMode.cpp
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
  Game/Source/GDKTestGyms/Public/TestGymsCharacterMovementComp.h
  Game/Source/GDKTestGyms/Public/TestGymsReplicationGraph.h
  Game/Source/GDKTestGyms/Public/UserExperienceComponent.h
  Game/Source/GDKTestGymsFunctionalTests/TestMaps/SpatialSingleWorkerTestGymMap.cpp
  spatial/workers/unreal/spatialos.StrategyWorker.worker.json
Labels: size/XXL, jira/no-ticket
