Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-09, with the labels that each got.

#452 Add custom schema components for partition metadata
  Game/Content/Spatial/PartitionMetadata/LegacyMetadata.schema
Labels: size/S, jira/no-ticket

#465 [UNR-5875] upgrade to worker sdk 15.3.1
  spatial/spatialos.json
Labels: jira/UNR, size/XS

#466 [UNR-5875] Update worker sdk to 15.1.1
  .buildkite/premerge.steps.yaml
  LaunchSpatial.bat
  UnrealGDKVersion.txt
  spatial/spatialos.json
Labels: jira/UNR, size/S

#464 [UNR-5651] 4.27 compatibility
  .buildkite/premerge.steps.yaml
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Labels: jira/UNR, size/S

#468 Update spatialos.json
  spatial/spatialos.json
Labels: size/XS, jira/no-ticket

#469 [UNR-5578] multiworker gym cube jitter
  Game/Content/Actors/NoNetLoadGymCube.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/XS
