Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-08, with the labels that each got.

#457 Update runtime and sdk to 15.2.0
  LaunchSpatial.bat
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#459 Fix for nonspatialized classes in Rep Graph
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Labels: size/XS, jira/no-ticket

#447 Disco-387
  Game/Config/DefaultEngine.ini
  Game/Content/Characters/ClientAuthPlayerCharacter_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedClientAuthPlayerCharacter_BP.uasset
  Game/Content/GameModes/BenchmarkGymGameMode.uasset
  Game/Content/GameModes/Disco387GymGameMode.uasset
  Game/Content/LoadBalancing/BP_Disco387_LBS.uasset
  Game/Content/LoadBalancing/BP_Disco387_Settings.uasset
  Game/Content/Maps/Disco387.umap
  Game/Source/GDKTestGyms/GDKTestGymsCharacter.cpp
  Game/Source/GDKTestGyms/GDKTestGymsCharacter.h
  Game/Source/GDKTestGyms/Private/Disco387GameStateBase.cpp
  Game/Source/GDKTestGyms/Private/TestGymsCharacterMovementComp.cpp
  Game/Source/GDKTestGyms/Public/Disco387GameStateBase.h
  Game/Source/GDKTestGyms/Public/TestGymsCharacterMovementComp.h
Labels: jira/no-ticket, size/L

#461 [UNR-5873] Upgrade Worker SDK and Runtime versions to 15.3.0
  LaunchSpatial.bat
  spatial/spatialos.json
Labels: jira/UNR, size/XS

#462 Fix player spawning clustering
  Game/Content/Benchmark/BenchmarkGymGameState.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Labels: size/XS, jira/no-ticket
