Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-04, with the labels that each got.

#335 [MBL-223]Call startfile/stopfile on a configurable interval for a configurable duration
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/MBL, size/M

#343 Repro of UNR-4146 commit
  Game/Content/Actors/CollisionCube.uasset
  Game/Content/Actors/CollisionSpawner.uasset
  Game/Content/Actors/PhysicsFloor.uasset
  Game/Content/Maps/KNOWN_ISSUE_CollisionHandoverGym.umap
Labels: jira/UNR, size/XS

#345 Disable Magic Leap plugins + Obsolete VR inputs plugins that were triggering WARNs
  Game/Config/DefaultInput.ini
  Game/GDKTestGyms.uproject
Labels: jira/UNR, size/S

#344 Adding worker_id to event trace events
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/UNR, size/XS

#339 MBL-221 add NPCs to uptime scenario
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/AUptimeGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/MBL, size/M

#347 [UNR-5150] Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/UNR, size/XS

#348 Fix labels and messages. Make new ci required.
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#350 Remove old CI
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/S

#341 MBL-224 cross server traffic
  Game/Content/Benchmark/UptimeGymGameState.uasset
  Game/Content/Characters/SimulatedPlayers/UptimeCrossServer_BP.uasset
  Game/Content/GameModes/UptimeGymGameMode.uasset
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/AUptimeGameMode.h
  Game/Source/GDKTestGyms/UptimeCrossServerBeacon.cpp
  Game/Source/GDKTestGyms/UptimeCrossServerBeacon.h
Labels: jira/MBL, size/L

#346 Test gym changes to manually test client disconnect
  Game/Content/Maps/PlayerDisconnectGym.umap
  Game/Content/PlayerDisconnectGym/PlayerDisconnectGameMode.uasset
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/Private/PlayerDisconnectController.cpp
  Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp
  Game/Source/GDKTestGyms/Public/PlayerDisconnectController.h
  Game/Source/GDKTestGyms/Public/UserExperienceComponent.h
  USER_MANUAL.md
Labels: jira/UNR, size/M

#351 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#353 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#356 Make the Server Take Damage RPC gym more comprehensible
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#354 feature/unr-5296-extend-test-setting-overrides-for-groups-of-maps-425
  Game/Config/MapSettingsOverrides/TestOverridesControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesEmpty.ini
  Game/Config/MapSettingsOverrides/TestOverridesLocalControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesLockedControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesMultiControllerPossessPawnGym.ini
  Game/Config/MapSettingsOverrides/TestOverridesOneClientGroup.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialCoreModeReplicationMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingGroup.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingZoningTests.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialNetReferenceMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialTearOffMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialTestCharacterMigrationMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialTestShutdownPreparationMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesSpatialZoningMap.ini
  Game/Config/MapSettingsOverrides/TestOverridesTestDebugInterface.ini
  Game/Config/MapSettingsOverrides/TestOverridesWorldCompositionGym.ini
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  Game/Content/Maps/FunctionalTests/SpatialTestShutdownPreparationMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart1Map.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart2Map.umap
  Game/Content/Maps/SpatialEventTracingZoningTests.umap
  Game/Content/Maps/WorldComposition/WorldCompositionGym.umap
Labels: jira/UNR, size/M

#358 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#359 Allow branch overriding for engine and GDK
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#362 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#355 UNR-5290: Optimizing event tracing to reduce overheads
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerComponent.uasset
  Game/Content/FunctionalTestSamples/BP_eventTracerCrossServerCube.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
Labels: jira/UNR, size/XS
