Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-05, with the labels that each got.

#361 RepGraph Test Actor when there is no PC
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
  Game/Source/GDKTestGyms/Public/TestGymsReplicationGraph.h
Labels: jira/UNR, size/S

#364 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#365 [UNR-5148] Test Crash In CrossServerMultiPossessionMap]
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Labels: jira/UNR, size/XS

#368 Fix "The config file will be staged, but is not whitelisted or blacklisted" WARNs
  Game/Config/DefaultGame.ini
Labels: jira/UNR, size/XS

#370 Replace dead reference of BP LB Strategy with up-to-date reference
  Game/Content/Maps/KNOWN_ISSUE_CollisionHandoverGym.umap
Labels: jira/UNR, size/XS

#369 Backwards compatibility for asset referencing assets saved on 4.26
  Game/Content/Latency/LatencyGameMode.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/UNR, size/XS

#357 [UNR-5273] Add cmd args for uptime gym
  Game/Source/GDKTestGyms/AUptimeGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Labels: jira/UNR, size/S

#360 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/M

#374 Fix/uptime expectation
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/XS

#363 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#377 UNR-5299 Destroy drop cube when player disconnects
  Game/Content/Benchmark/SpawnDestroyCube_BP.uasset
Labels: jira/UNR, size/XS

#376 Fixing event tracing test failures
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerComponent.uasset
  Game/Content/FunctionalTestSamples/BP_eventTracerCrossServerCube.uasset
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  Game/Content/Maps/SpatialEventTracingZoningTests.umap
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
Labels: jira/UNR, size/XS

#379 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#378 UNR-5298 Feature/movement expectation
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  Game/Source/GDKTestGyms/Private/NFRConstants.cpp
  Game/Source/GDKTestGyms/Public/NFRConstants.h
Labels: jira/UNR, size/L

#366 [UNR-5415] RPC timeout test gym
  Game/Content/Maps/RPCTimeoutTestGym.umap
  Game/Content/SoftReferenceTest/Green1.uasset
  Game/Content/SoftReferenceTest/MaterialArray.uasset
  Game/Content/SoftReferenceTest/RPCTimeoutGameMode.uasset
  Game/Content/SoftReferenceTest/RPCTimeoutPC.uasset
  Game/Content/SoftReferenceTest/Red.uasset
  USER_MANUAL.md
Labels: jira/UNR, size/S

#382 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#386 Fix the LatencyPlayerCharacter broken nodes
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#385 Bugfix/unr-5463
  Game/Content/Actors/GymCube.uasset
  Game/Content/LoadBalancing/BP_1x2_FullInterestLBStrategy.uasset
  Game/Content/LoadBalancing/BP_1x2_NoInterestLBStrategy.uasset
  Game/Content/LoadBalancing/BP_FullInterest_1x2_MultiWorkerSettings.uasset
  Game/Content/LoadBalancing/BP_FullInterest_1x2_MultiWorkerSettings1.uasset
  Game/Content/LoadBalancing/BP_NoInterest_1x2_MultiWorkerSettings.uasset
  Game/Content/LoadBalancing/NoInterest_1x2_MultiWorkerSettings.uasset
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningBlueprintTests.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningDelegationWithoutBorderMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialZoningVariableReplicationWithoutBorderMap.umap
  Game/Content/Maps/KNOWN_ISSUE_CollisionHandoverGym.umap
  Game/Content/Maps/MultiworkerWorldComposition/MultiworkerWorldComposition.umap
Labels: jira/UNR, size/XS

#388 Updating to new CI version 1.3
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#391 Fix latency game mode defaults
  Game/Content/Latency/LatencyGameMode.uasset
Labels: jira/UNR, size/XS

#373 Disconnect clients in test framework
  Game/Content/Maps/PlayerDisconnectGym.umap
  Game/Content/PlayerDisconnectGym/PlayerDisconnectGameMode.uasset
  Game/Source/GDKTestGyms/Private/PlayerDisconnectController.cpp
  Game/Source/GDKTestGyms/Public/PlayerDisconnectController.h
  USER_MANUAL.md
Labels: jira/UNR, size/M

#383 [UNR-5548] Add Visual Logger manual test gym
  Game/Content/Actors/VisualLoggerGymCube.uasset
  Game/Content/Actors/VisualLoggerStationaryGymCube.uasset
  Game/Content/Maps/VisualLogger/VisualLoggerManualTest.umap
  USER_MANUAL.md
Labels: jira/UNR, size/M

#390 unr-5582-fix-settings-override-path
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  Game/Content/Maps/FunctionalTests/SpatialTestShutdownPreparationMap.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart1Map.umap
  Game/Content/Maps/FunctionalTests_samples/SpatialSnapshotTestPart2Map.umap
  Game/Content/Maps/SpatialEventTracingZoningTests.umap
  Game/Content/Maps/WorldComposition/WorldCompositionGym.umap
Labels: jira/UNR, size/XS

#393 Fix client count metric
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Labels: jira/no-ticket, size/S

#396 Cherry-pick of "Fix latency game mode defaults (#391)"
  Game/Content/Latency/LatencyGameMode.uasset
Labels: jira/no-ticket, size/XS

#394 Update premerge.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/XS

#398 Cherry pick "UNR-5290: Optimizing event tracing to reduce overheads (#355)"
  Game/Content/FunctionalTestSamples/BP_EventTracerCharacter.uasset
  Game/Content/FunctionalTestSamples/BP_EventTracerComponent.uasset
  Game/Content/FunctionalTestSamples/BP_eventTracerCrossServerCube.uasset
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
  Game/Source/GDKTestGyms/Private/EventTracerComponent.cpp
Labels: jira/UNR, size/XS

#402 Pick latency character fix
  Game/Content/Latency/LatencyPlayerCharacter_BP.uasset
Labels: jira/no-ticket, size/XS

#380 UNR-5541 - Improve the log message
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
Labels: jira/UNR, size/XS

#403 UNR-5611 Ability to do a 5x5 deployment for uptime testing
  Game/Content/LoadBalancing/BP_BenchmarkGym_Settings_Zoning5_5.uasset
  Game/Content/LoadBalancing/BP_BenchmarkGym_Zoning5_5.uasset
Labels: jira/UNR, size/XS

#401 Feature/unr 5198 et debugger v2 0.13
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/EventTracing/BP_ETSamplingSettings_Default.uasset
  Game/Content/EventTracing/BP_ETSamplingSettings_latencygym.uasset
Labels: jira/UNR, size/XS

#400 Bugfix/unr-5543
  Game/Content/Characters/SimulatedPlayers/BTTask_BenchmarkNPC_SwapTarget.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_BP.uasset
  Game/Content/Characters/SimulatedPlayers/BenchmarkNPC_TargetStateEnum.uasset
  Game/Content/Characters/SimulatedPlayers/OffloadedNPCAIController_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerBehaviorTree_BP.uasset
  Game/Content/Characters/SimulatedPlayers/SimulatedPlayerBlackboard_BP.uasset
  Game/Source/GDKTestGyms/Private/BenchmarkNPCCharacter.cpp
  Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/BenchmarkNPCCharacter.h
  Game/Source/GDKTestGyms/Public/BlackboardValues.cpp
  Game/Source/GDKTestGyms/Public/BlackboardValues.h
  Game/Source/GDKTestGyms/Public/DeterministicBlackboardValues.h
Labels: jira/UNR, size/M
