Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2021-01, with the labels that each got.

#256 UNR-4462: Added a functional test to check for game mode replication
  Game/Content/Maps/FunctionalTests/SpatialGameModeReplicationMap.umap
Labels: jira/UNR, size/XS

#261 Add functional test map as a 4.24 asset
  Game/Content/FunctionalTestSamples/BP_1x2_SmallInterest_WorkerSettings.uasset
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialCleanupConnectionTest.umap
Labels: jira/no-ticket, size/XS

#262 UNR-4459 fixed up dynamic components gym blueprint to not generate too many subobjects
  Game/Content/Controllers/DynamicComponentsPlayerController.uasset
Labels: jira/UNR, size/XS

#265 Upgrade preview 7
  spatial/spatialos.json
Labels: jira/PREVIEW, size/XS

#266 Tell test users to generate schema and snapshot.
  USER_MANUAL.md
Labels: jira/no-ticket, size/M

#264 New test map for testing spatial component callbacks
  Game/Content/Maps/FunctionalTests/CI_Fast/SpatialComponentMap.umap
Labels: jira/no-ticket, size/XS

#269 Adding event tracing functional test instructions
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#268 Recreation of SpatialZoningMap in 4.24
  Game/Content/FunctionalTestSamples/BP_1x2_WorkerSettings.uasset
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
Labels: jira/no-ticket, size/XS

#259 [UNR-4529] Cross-server ability activation functional test
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
Labels: jira/UNR, size/XS

#272 Add PredictedGameplayCuesTest to SpatialZoningMap
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
Labels: jira/no-ticket, size/XS

#270 Update to preview 8
  spatial/spatialos.json
Labels: jira/PREVIEW, size/XS

#273 Disable gameplay cues test until it is fixed
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
Labels: jira/no-ticket, size/XS

#274 Revert handover gym to full lbs
  Game/Content/LoadBalancing/BP_QuadrantSmallLBStrategy.uasset
  Game/Content/LoadBalancing/BP_QuadrantSmallZoningSettings.uasset
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
Labels: jira/UNR, size/XS

#275 Clarify the ReplicatedStartupActor gym steps.
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#277 Note that ServerTravel is not suppoted.
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#271 UNR-4811
  USER_MANUAL.md
Labels: jira/UNR, size/S

#260 UNR-4582 Remote possession test map and resources
  Game/Content/LoadBalancing/BP_Possession_Settings_Zoning2_2.uasset
  Game/Content/LoadBalancing/BP_Possession_Zoning2_2.uasset
  Game/Content/Maps/PossessionGym.umap
  Game/Content/Possession/CustomerRemotePossessionComponent.uasset
Labels: jira/UNR, size/XS

#281 Update the manual and fix a couple of blueprint warnings.
  Game/Content/Controllers/MultipleOwnershipController.uasset
  Game/Content/Maps/MultipleOwnershipGym.umap
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#279 [UNR-4827] Move GAS tests into GDKTestGyms
  Game/Content/Maps/FunctionalTests/CI_Fast_Spatial_Only/SpatialZoningMap.umap
  Game/GDKTestGyms.uproject
  Game/Source/GDKTestGymsEditor.Target.cs
  Game/Source/GDKTestGymsFunctionalTests/GDKTestGymsFunctionalTests.Build.cs
  Game/Source/GDKTestGymsFunctionalTests/GDKTestGymsFunctionalTests.cpp
  Game/Source/GDKTestGymsFunctionalTests/GDKTestGymsFunctionalTests.h
  Game/Source/GDKTestGymsFunctionalTests/Public/LogGymsSpatialFunctionalTest.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/CrossServerAbilityActivationTest.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/CrossServerAbilityActivationTest.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/GA_IncrementSpyValue.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/GA_IncrementSpyValue.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/SpyValueGASTestActor.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/CrossServerAbilityActivationTest/SpyValueGASTestActor.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/CuesGASTestPawn.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/CuesGASTestPawn.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GA_ApplyCueEffect.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GA_ApplyCueEffect.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GC_SignalCueActivation.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GC_SignalCueActivation.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GE_AddCue.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GE_AddCue.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GE_ExecuteCue.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/GE_ExecuteCue.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/PredictedGameplayCuesTest.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/PredictedGameplayCuesTest/PredictedGameplayCuesTest.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestActorBase.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestActorBase.h
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestPawnBase.cpp
  Game/Source/GDKTestGymsFunctionalTests/Tests/TestActors/GASTestPawnBase.h
Labels: jira/UNR, size/XXL

#278 Fixed BP and map warnings
  Game/Content/Actors/OffloadableGymCube.uasset
  Game/Content/LoadBalancing/BP_oflgym_Offloaded_Settings.uasset
  Game/Content/Maps/OffloadingBenchmarkGymTiny.umap
Labels: jira/UNR, size/XS

#283 Clarify DestroyStartupActorGym test gym steps.
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#284 Clarify Latency gym steps.
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#287 Rename failing test to include KNOWN_ISSUE
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
Labels: jira/no-ticket, size/XS

#289 Updating worker flags gym.
  Game/Content/Maps/WorkerFlagsGym.umap
  Game/Content/Maps/WorkerFlagsGym_BuiltData.uasset
  USER_MANUAL.md
  spatial/workerflags_testgym_config.json
Labels: jira/UNR, size/M

#288 Clarify Teleporting gym steps
  USER_MANUAL.md
Labels: jira/UNR, size/S

#285 Fixing flake in NFRs to do with player count
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Labels: jira/no-ticket, size/S

#291 Merging 0.12.0-rc back into master
  Game/Content/Actors/OffloadableGymCube.uasset
  Game/Content/LoadBalancing/BP_QuadrantSmallLBStrategy.uasset
  Game/Content/LoadBalancing/BP_QuadrantSmallZoningSettings.uasset
  Game/Content/LoadBalancing/BP_oflgym_Offloaded_Settings.uasset
  Game/Content/Maps/FunctionalTests/SpatialEventTracingTests.umap
  Game/Content/Maps/HandoverGym.umap
  Game/Content/Maps/HandoverGym_BuiltData.uasset
  Game/Content/Maps/OffloadingBenchmarkGymTiny.umap
  Game/Content/Maps/WorkerFlagsGym.umap
  Game/Content/Maps/WorkerFlagsGym_BuiltData.uasset
  Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
  Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
  USER_MANUAL.md
  spatial/spatialos.json
  spatial/workerflags_testgym_config.json
Labels: jira/no-ticket, size/L

#243 Feature/add multiworker world comp
  Game/Content/Actors/NoNetLoadGymCube.uasset
  Game/Content/GameModes/MultiworkerWorldCompositionGameMode.uasset
  Game/Content/Maps/MultiworkerWorldComposition/MultiworkerWorldComposition.umap
  Game/Content/Maps/MultiworkerWorldComposition/Sublevel1.umap
  Game/Content/Maps/MultiworkerWorldComposition/Sublevel2.umap
  Game/Content/TeleportingGym/TeleportingPlayerController.uasset
  Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
  Game/Source/GDKTestGymsEditor.Target.cs
  USER_MANUAL.md
Labels: jira/no-ticket, size/L

#280 Map changes for fix USpatialNetDriver::ProcessRPC incorrectly allocating an entity id
  Game/Content/Maps/FunctionalTests/SpatialTestCrossServerRPCMap.umap
Labels: jira/UNR, size/XS

#290 Clarifying FASHandover gym steps
  USER_MANUAL.md
Labels: jira/UNR, size/XS

#292 Update `SpatialDebuggerConfigUIGym` steps.
  USER_MANUAL.md
Labels: jira/UNR, size/S

#296 Clarify `GameplayCuesMap` steps.
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#293 Upgrade to 15.0.0
  DeployGame.bat
  LaunchSpatial.bat
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#297 Clarifies `Client Travel gym` test steps.
  USER_MANUAL.md
Labels: jira/no-ticket, size/S

#295 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: jira/no-ticket, size/XS

#298 UNR-4743: Added a test gym for missing schema
  Game/Config/DefaultGame.ini
  Game/Content/Actors/NeverCook/MissingSchemaCube.uasset
  Game/Content/Controllers/MissingSchemaPlayerController.uasset
  Game/Content/GameModes/MissingSchemaGymGameMode.uasset
  Game/Content/Maps/MissingSchemaGym.umap
Labels: jira/UNR, size/XS

#302 Test: Snapshot reloading.
  USER_MANUAL.md
Labels: jira/UNR, size/XS
