Repository spatialos/UnrealGDKTestGyms, pull requests merged in 2022-01, with the labels that each got.

#479 Updated setting path
  USER_MANUAL.md
Labels: size/XS, jira/no-ticket

#480 Update USER_MANUAL.md
  USER_MANUAL.md
Labels: size/XS, jira/no-ticket

#482 Update user manual link
  README.md
Labels: size/XS, jira/no-ticket

#429 Player disconnect update user manual
  Game/Content/Maps/PlayerDisconnectGym.umap
  USER_MANUAL.md
Labels: size/XS, jira/no-ticket

#454 add note to multiworker gym about buggy movement with bnetloadonclient cubes
  USER_MANUAL.md
Labels: size/XS, jira/no-ticket

#299 [UNR-4585] Replay test gym
  Game/Content/Actors/ServerOnlyCube.uasset
  Game/Content/Characters/NothingSpecialCharacter_BP.uasset
  Game/Content/GameModes/NothingSpecialGameMode.uasset
  Game/Content/Maps/ReplayGym.umap
  Game/Content/Maps/ReplayGym_BuiltData.uasset
  Game/Source/GDKTestGyms.Target.cs
  Game/Source/GDKTestGyms/Private/ReplayPlayerController.cpp
  Game/Source/GDKTestGyms/Public/ReplayPlayerController.h
  Game/Source/GDKTestGymsClient.Target.cs
  Game/Source/GDKTestGymsEditor.Target.cs
  Game/Source/GDKTestGymsServer.Target.cs
  USER_MANUAL.md
Labels: size/M, jira/UNR

#483 UNR-5057: Unity builds
  .buildkite/premerge.steps.yaml
Labels: jira/UNR, size/XS
